development: &development
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: netzke-demo_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: netzke-demo_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: netzke-demo_production
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

profiling:
  <<: *development